### ISSUE TITLE
Update "group" to "conference" API & update to stateless callbacks.

### ISSUE THREAD

**Issue by iphydf** [suhr/rstox#24]
In https://github.com/TokTok/c-toxcore we have made old group chats a first class supported API and rebranded it as conference. The new group chats will be called "group". We have also removed user data from callback registration functions. This now needs to be passed to tox_iterate.

So, you can remove the "KLUDGE" comments and use the proper API now.

**Comment by iphydf** [comment]
FYI: tox development is no longer non-public (whatever that meant). We are publicly developing it with a roadmap and plan: http://toktok.github.io/plan.

**Comment by suhr** [comment]
> we have made old group chats a first class supported API and rebranded it as conference

This solution is rather a kludge too.

> We are publicly developing it with a roadmap and plan: http://toktok.github.io/plan

Great (so, toktok is official?). I'm not focused on developing rstox though.
But I'll fix the README ~later.

**Comment by kpp** [comment]
@iphydf shall we name group chats as conferences and what about ngc?
