### ISSUE TITLE
Panic in tox_new()

### ISSUE THREAD

**Issue by JFreegman** [suhr/rstox#36]
`thread 'main' panicked at 'attempted to leave type `core::errors::InitError` uninitialized, which is invalid', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/mem/mod.rs:664:9`

**Comment by JFreegman** [comment]
This appears to be stemming from the usage of `mem::uninitialized()` which has been recently deprecated due to it causing UB.

**Comment by kpp** [comment]
Oh...
